### ISSUE TITLE
Big padding on top

### ISSUE THREAD

**Issue by adro79** [LucyUwI/Pocket#4]
Hello there,

I just came across with your theme in the Spicetify Marketplace and I liked it, but seems like it has this big padding on top that makes it unusable.

I tried both the marketplace installation and the script.

I'm using Arch Linux and everything's updated.

![image](https://user-images.githubusercontent.com/57686179/222960259-383f79a0-6849-4a29-b555-d83e07ffaaa5.png)

**Comment by lichenophile** [comment]
Same.

the padding seems to disappear when I input text into the playlist filter
